# Generated by Django 2.2.20 on 2021-05-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
