# Generated by Django 2.2.20 on 2021-05-27 11:57

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0002_idea_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
