# Generated by Django 2.2.19 on 2021-03-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0003_idea_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='idea'),
        ),
    ]
