# Generated by Django 2.2.20 on 2021-05-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20210530_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='app_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
