# Generated by Django 2.2.19 on 2021-03-15 17:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0004_auto_20210310_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
