# Generated by Django 2.2.20 on 2021-05-30 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0005_idea_app_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='idea.IdeaStatus', verbose_name='Idea Status'),
        ),
    ]
