# Generated by Django 2.2.20 on 2021-09-22 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0007_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('files', models.FileField(blank=True, null=True, upload_to='blog')),
                ('title', models.TextField()),
                ('api_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
