# Generated by Django 2.2.20 on 2021-09-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0008_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='tags',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
