# Generated by Django 2.2.20 on 2021-09-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0009_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
