# Generated by Django 2.2.20 on 2021-10-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0010_auto_20210923_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='html_rapport',
            field=models.FileField(blank=True, null=True, upload_to='idea'),
        ),
    ]
