# Generated by Django 2.2.20 on 2021-10-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea', '0011_blog_html_rapport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='html_rapport',
            field=models.FileField(blank=True, null=True, upload_to='rapports'),
        ),
    ]
